import java.util.*;
import java.io.*;
import java.math.*;

/**
 * THis is my customization of the provided CodinGame AutoGenerated code to solve the problem.
 **/
class Solution {

    public static void main(String args[]) {
        Scanner in = new Scanner(System.in);
        int N = in.nextInt(); // the number of temperatures to analyse
        in.nextLine();
        
        // Handler for cases where no temperatures are proided
        // Might be a more implicit way to do this, but its easy to eliminate early.
        if (!in.hasNext()) System.out.println("0");
        else {
            // Read the individual temperatures, assume the first is the closes to zero.
            int closestToZero = in.nextInt(); // the N temperatures expressed as integers ranging from -273 to 5526
            
            while (in.hasNext())
            {
                int nextTemp = in.nextInt();
                // Check each temperature and determine if it is closer to Zero than the current assumed closest.
                if (Math.abs(nextTemp) < Math.abs(closestToZero)) closestToZero = nextTemp;
                // This check is based on the rule that if 2 temps are equally close, but on opposite sides (+5 and -5);
                // then the positive integer (+5) is to be used.
                if ((Math.abs(nextTemp) == Math.abs(closestToZero)) && (nextTemp > 0)) closestToZero = nextTemp;
            }

            // Write an action using System.out.println()
            // To debug: System.err.println("Debug messages...");

            System.out.println(closestToZero);
        }
    }
}
